### ISSUE TITLE
Parse Error in command

### ISSUE THREAD

**Issue by tannerbaum** [moritzjacobs/alium#2]
Here is a screenshot of the command I attempted to alias and the response I received. 

<img width="802" alt="Screenshot 2019-10-02 at 17 46 55" src="https://user-images.githubusercontent.com/1280597/66059722-ca84a580-e53c-11e9-9198-972c68f85442.png">

**Comment by moritzjacobs** [comment]
I can tell from the emoji in the screenshot, that you use an older version. Does this still happen with a more recent version of alium?

**Comment by moritzjacobs** [comment]
Upon further inspection, the command you saved is erroneous. The `; &&` indeed is wrong and should throw an error.
